<?php

namespace App\Modules\Notifications\Models;

use App\Core\DatabaseInterface;

/**
 * All database queries for module_notifications and module_notification_deliveries.
 *
 * This repository is fully decoupled from any NetMon-specific model.
 * It has no dependency on DeviceRepository, AlertRepository, or any class
 * outside the kernel (App\Core\) and this module.
 *
 * Returns raw arrays; no domain objects.
 */
class NotificationRepository
{
    private DatabaseInterface $db;

    public function __construct(DatabaseInterface $db)
    {
        $this->db = $db;
    }

    // -------------------------------------------------------------------------
    // Notifications
    // -------------------------------------------------------------------------

    /**
     * Insert a new notification event row.
     *
     * @param  array{
     *   source_type: string|null,
     *   source_id:   int|null,
     *   title:       string,
     *   body:        string,
     *   data:        string|null
     * } $data
     * @return int  New notification ID
     */
    public function createNotification(array $data): int
    {
        $this->db->execute(
            "INSERT INTO module_notifications
                 (source_type, source_id, title, body, data, created_at)
             VALUES (?, ?, ?, ?, ?, ?)",
            [
                $data['source_type'] ?? null,
                $data['source_id']   ?? null,
                $data['title'],
                $data['body'],
                $data['data']        ?? null,
                date('Y-m-d H:i:s'),
            ]
        );

        return (int) $this->db->lastInsertId();
    }

    /**
     * Return all notifications for a given source entity (e.g. all notifications
     * that were generated by alert #3).
     */
    public function findBySource(string $sourceType, int $sourceId): array
    {
        return $this->db->fetch(
            "SELECT * FROM module_notifications
             WHERE  source_type = ? AND source_id = ?
             ORDER  BY created_at DESC",
            [$sourceType, $sourceId]
        );
    }

    // -------------------------------------------------------------------------
    // Deliveries
    // -------------------------------------------------------------------------

    /**
     * Insert a new delivery record (initially status='pending').
     *
     * @param  array{
     *   notification_id: int,
     *   user_id:         int,
     *   channel:         string
     * } $data
     * @return int  New delivery ID
     */
    public function createDelivery(array $data): int
    {
        $this->db->execute(
            "INSERT INTO module_notification_deliveries
                 (notification_id, user_id, channel, status, created_at)
             VALUES (?, ?, ?, 'pending', ?)",
            [
                $data['notification_id'],
                $data['user_id'],
                $data['channel'],
                date('Y-m-d H:i:s'),
            ]
        );

        return (int) $this->db->lastInsertId();
    }

    /**
     * Update fields on a delivery record.
     * Accepts any subset of: status, sent_at, read_at, error.
     */
    public function updateDelivery(int $deliveryId, array $fields): void
    {
        if (empty($fields)) {
            return;
        }

        $allowed = ['status', 'sent_at', 'read_at', 'error'];
        $sets    = [];
        $values  = [];

        foreach ($allowed as $col) {
            if (array_key_exists($col, $fields)) {
                $sets[]  = "$col = ?";
                $values[] = $fields[$col];
            }
        }

        if (empty($sets)) {
            return;
        }

        $values[] = $deliveryId;

        $this->db->execute(
            "UPDATE module_notification_deliveries SET " . implode(', ', $sets) . " WHERE id = ?",
            $values
        );
    }

    /**
     * Find a single delivery by ID, with notification content JOINed.
     * Returns null if not found.
     */
    public function findDeliveryById(int $id): ?array
    {
        return $this->db->fetchOne(
            "SELECT
                d.id,
                d.notification_id,
                d.user_id,
                d.channel,
                d.status,
                d.read_at,
                d.sent_at,
                d.error,
                d.created_at,
                n.source_type,
                n.source_id,
                n.title,
                n.body,
                n.data
            FROM   module_notification_deliveries d
            JOIN   module_notifications n ON n.id = d.notification_id
            WHERE  d.id = ?",
            [$id]
        );
    }

    // -------------------------------------------------------------------------
    // Inbox — in_app channel
    // -------------------------------------------------------------------------

    /**
     * Return in_app deliveries for a user, newest first.
     *
     * Returns all sent in_app deliveries (read and unread) up to $limit.
     * Includes the notification content (title, body, source_*, data) via JOIN.
     *
     * @return array<int, array{
     *   id:              int,
     *   notification_id: int,
     *   user_id:         int,
     *   channel:         string,
     *   status:          string,
     *   read_at:         string|null,
     *   sent_at:         string|null,
     *   created_at:      string,
     *   source_type:     string|null,
     *   source_id:       int|null,
     *   title:           string,
     *   body:            string,
     *   data:            string|null
     * }>
     */
    public function findByUser(int $userId, int $limit = 50): array
    {
        return $this->db->fetch(
            "SELECT
                d.id,
                d.notification_id,
                d.user_id,
                d.channel,
                d.status,
                d.read_at,
                d.sent_at,
                d.created_at,
                n.source_type,
                n.source_id,
                n.title,
                n.body,
                n.data
            FROM   module_notification_deliveries d
            JOIN   module_notifications n ON n.id = d.notification_id
            WHERE  d.user_id = ?
              AND  d.channel = 'in_app'
              AND  d.status  = 'sent'
            ORDER  BY d.created_at DESC
            LIMIT  ?",
            [$userId, $limit]
        );
    }

    /**
     * Return only unread in_app deliveries for a user, newest first.
     */
    public function findUnreadByUser(int $userId, int $limit = 50): array
    {
        return $this->db->fetch(
            "SELECT
                d.id,
                d.notification_id,
                d.user_id,
                d.channel,
                d.status,
                d.read_at,
                d.sent_at,
                d.created_at,
                n.source_type,
                n.source_id,
                n.title,
                n.body,
                n.data
            FROM   module_notification_deliveries d
            JOIN   module_notifications n ON n.id = d.notification_id
            WHERE  d.user_id = ?
              AND  d.channel = 'in_app'
              AND  d.status  = 'sent'
              AND  d.read_at IS NULL
            ORDER  BY d.created_at DESC
            LIMIT  ?",
            [$userId, $limit]
        );
    }

    /**
     * Count unread in_app deliveries for a user.
     * Used for the topbar badge.
     */
    public function countUnreadByUser(int $userId): int
    {
        $row = $this->db->fetchOne(
            "SELECT COUNT(*) AS cnt
             FROM   module_notification_deliveries
             WHERE  user_id = ?
               AND  channel = 'in_app'
               AND  status  = 'sent'
               AND  read_at IS NULL",
            [$userId]
        );

        return (int) ($row['cnt'] ?? 0);
    }

    /**
     * Mark a single in_app delivery as read.
     * Sets read_at to now. Idempotent — re-reading an already-read delivery
     * does not change read_at.
     */
    public function markRead(int $deliveryId): void
    {
        $this->db->execute(
            "UPDATE module_notification_deliveries
             SET    read_at = ?
             WHERE  id      = ?
               AND  channel = 'in_app'
               AND  read_at IS NULL",
            [date('Y-m-d H:i:s'), $deliveryId]
        );
    }

    /**
     * Mark all unread in_app deliveries for a user as read.
     */
    public function markAllReadByUser(int $userId): void
    {
        $this->db->execute(
            "UPDATE module_notification_deliveries
             SET    read_at = ?
             WHERE  user_id = ?
               AND  channel = 'in_app'
               AND  status  = 'sent'
               AND  read_at IS NULL",
            [date('Y-m-d H:i:s'), $userId]
        );
    }
}
