<?php

namespace App\Core\Installer;

/**
 * Writes installer-generated configuration to .env and config/local.php.
 *
 * .env writing strategy
 * ---------------------
 * Existing lines are preserved as-is.  Only the specific keys passed in
 * $updates are modified.  If a key already exists in the file, its line is
 * updated in place.  If it does not exist, it is appended at the end.
 * Comments and blank lines are never removed.
 *
 * config/local.php writing strategy
 * ----------------------------------
 * The file is generated fresh from the provided array.  It uses a simple
 * recursive formatter that produces readable indented PHP rather than the
 * compact output of var_export().
 */
class ConfigWriter
{
    // -------------------------------------------------------------------------
    // .env
    // -------------------------------------------------------------------------

    /**
     * Update specific key=value pairs in a .env file.
     *
     * Creates the file if it does not exist.
     * Preserves all existing lines; updates matching keys in-place;
     * appends keys that are not yet present.
     *
     * @param  string              $path     Absolute path to the .env file.
     * @param  array<string,mixed> $updates  Keys and their new values.
     * @throws \RuntimeException   if the file cannot be written.
     */
    public function writeEnv(string $path, array $updates): void
    {
        $lines   = [];
        $handled = [];

        if (file_exists($path)) {
            $lines = file($path, FILE_IGNORE_NEW_LINES) ?: [];
        }

        // Pass 1 — update existing key lines
        foreach ($lines as &$line) {
            if (preg_match('/^([A-Z_][A-Z0-9_]*)\s*=/i', $line, $m)) {
                $key = $m[1];
                if (array_key_exists($key, $updates)) {
                    $line      = $key . '=' . $this->formatValue((string) $updates[$key]);
                    $handled[] = $key;
                }
            }
        }
        unset($line);

        // Pass 2 — append keys not found in the existing file
        foreach ($updates as $key => $value) {
            if (!in_array($key, $handled, true)) {
                $lines[] = $key . '=' . $this->formatValue((string) $value);
            }
        }

        $result = file_put_contents($path, implode(PHP_EOL, $lines) . PHP_EOL);

        if ($result === false) {
            throw new \RuntimeException("Could not write .env file: {$path}");
        }
    }

    // -------------------------------------------------------------------------
    // config/local.php
    // -------------------------------------------------------------------------

    /**
     * Write a config/local.php file from a structured PHP array.
     *
     * The array is formatted with clean indentation.  The file is written
     * fresh on each call (previous local.php is replaced entirely).
     *
     * @param  string $path     Absolute path to local.php.
     * @param  array  $config   Config values keyed by config-file name
     *                          (e.g. ['database' => ['driver' => 'sqlite']]).
     * @throws \RuntimeException if the file cannot be written.
     */
    public function writeLocalPhp(string $path, array $config): void
    {
        $date   = date('Y-m-d H:i:s');
        $array  = $this->formatArray($config, 0);

        // Build as a plain string — heredoc indentation stripping would also
        // strip intentional indentation inside the formatted array.
        $content = '<?php' . PHP_EOL
            . PHP_EOL
            . '/**' . PHP_EOL
            . ' * Local configuration overrides — generated by installer on ' . $date . '.' . PHP_EOL
            . ' * Do not commit this file to version control.' . PHP_EOL
            . ' *' . PHP_EOL
            . ' * To regenerate, run the installer again.' . PHP_EOL
            . ' */' . PHP_EOL
            . 'return ' . $array . ';' . PHP_EOL;

        $result = file_put_contents($path, $content);

        if ($result === false) {
            throw new \RuntimeException("Could not write local.php: {$path}");
        }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    /**
     * Format a .env value, quoting it if it contains whitespace or special
     * characters that could confuse a line-by-line parser.
     */
    private function formatValue(string $value): string
    {
        if ($value === '' || preg_match('/[\s#"\'\\\\]/', $value)) {
            return '"' . str_replace(['"', '\\'], ['\\"', '\\\\'], $value) . '"';
        }

        return $value;
    }

    /**
     * Recursively format a PHP array with clean indentation.
     *
     * Produces readable output like:
     *   [
     *       'driver' => 'sqlite',
     *       'mysql'  => [
     *           'host' => '127.0.0.1',
     *       ],
     *   ]
     */
    private function formatArray(array $data, int $depth): string
    {
        if (empty($data)) {
            return '[]';
        }

        $pad   = str_repeat('    ', $depth);
        $child = str_repeat('    ', $depth + 1);
        $lines = [];

        foreach ($data as $key => $value) {
            $k = is_int($key) ? (string) $key : "'{$key}'";
            $v = $this->formatScalar($value, $depth);
            $lines[] = "{$child}{$k} => {$v},";
        }

        return "[\n" . implode("\n", $lines) . "\n{$pad}]";
    }

    private function formatScalar(mixed $value, int $depth): string
    {
        return match (true) {
            is_array($value)  => $this->formatArray($value, $depth + 1),
            is_bool($value)   => $value ? 'true' : 'false',
            is_null($value)   => 'null',
            is_int($value)    => (string) $value,
            is_float($value)  => (string) $value,
            default           => "'" . str_replace("'", "\\'", (string) $value) . "'",
        };
    }
}
